# -*- coding: utf-8 -*-
"""DesafioS2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eEdhCcg8yPlMKZ_lJfoVGUZH0K7oW-RZ
"""

import pandas as pd
uri = "https://raw.githubusercontent.com/fivethirtyeight/data/master/murder_2016/murder_2015_final.csv"
murder = pd.read_csv(uri, error_bad_lines=False, encoding='latin-1')
murder.head()

murder.plot(kind='hist')